# Generated by Django 2.0.3 on 2018-04-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180410_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomLinks',
            new_name='CustomLink',
        ),
    ]
